const LOAD_MEALS = 'LOAD_MEALS';
const SELECT_CATEGORY = 'SELECT_CATEGORY';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const LOG_USER_IN = 'LOG_USER_IN';
const LOG_USER_OUT = 'LOG_USER_OUT';
const VALIDATE_USER = 'VALIDATE_USER';
const VALIDATION_ERROR = 'VALIDATION_ERROR';
const REGISTER_USER = 'REGISTER_USER';
const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export { 
  LOAD_MEALS, SELECT_CATEGORY, ADD_TO_CART, REMOVE_FROM_CART, LOG_USER_IN, LOG_USER_OUT, 
  VALIDATE_USER, VALIDATION_ERROR, REGISTER_USER, REGISTRATION_ERROR
};
