const LOAD_MEALS = 'LOAD_MEALS';
const SELECT_CATEGORY = 'SELECT_CATEGORY';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export { LOAD_MEALS, SELECT_CATEGORY, ADD_TO_CART, REMOVE_FROM_CART };
